#!/usr/bin/env bun

const res = await fetch(
  "https://raw.githubusercontent.com/signalapp/Signal-Desktop/refs/heads/main/config/default.json",
);

if (!res.ok) {
  console.error(
    `Failed to fetch Signal Desktop's default config: ${res.status} ${res.statusText}`,
  );
  process.exit(1);
}

const defaultConfig = await res.json();

if (
  !defaultConfig ||
  typeof defaultConfig !== "object" ||
  !("certificateAuthority" in defaultConfig) ||
  typeof defaultConfig.certificateAuthority !== "string" ||
  !/^[\w\n +/-]+$/i.test(defaultConfig.certificateAuthority)
) {
  console.error(
    "Failed to validate Signal Desktop's default config structure.",
  );
  process.exit(1);
}

let currentCaPem = "";
try {
  currentCaPem = (await import("../src/signalCa")).SIGNAL_CA_PEM;
} catch (e) {
  if (!e || !/cannot find module/i.test(e.toString())) {
    throw e;
  }
}

if (currentCaPem && defaultConfig.certificateAuthority === currentCaPem) {
  console.log("Signal CA PEM is up to date, no changes needed.");
  process.exit(0);
}

await Bun.write(
  "src/signalCa.ts",
  `\
// Signal Messenger's self-signed root CA. Signal's CDN and chat servers present
// certificates signed by this CA rather than a publicly-trusted one, so any
// direct HTTPS requests (e.g. attachment downloads from cdn*.signal.org) must
// trust it explicitly.
//
// Kept in sync with Signal-Desktop's default config by \`bun run fetch-ca\`.
// DO NOT EDIT THIS FILE MANUALLY.

export const SIGNAL_CA_PEM = \`${defaultConfig.certificateAuthority}\`;
`,
);

console.log("Updated Signal CA PEM in src/signalCa.ts");
